id: P000290
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 2021-12-16 15:32:16.718782
source_metadata:
  id: bdr:W1AC227
  title: 'ཆོས་རྒྱལ་རབ་བརྟན་ཀུན་བཟང་འཕགས་ཀྱི་རྣམ་ཐར། '
  author: ''
  volumes:
    60d12f9a5fd64cbbba77d1d4b9b446ce:
      image_group_id: I2PD18725
      title: Volume 1 of chos rgyal rab brtan kun bzang 'phags kyi rnam thar/
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
